name: Terraform Destroy

on:
  #workflow_dispatch:  # This triggers the workflow manually via GitHub UI
  push:
    branches:
     - main  # Trigger on pushes to the main branch

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1  # Set your region here
        run: |
          terraform init
          terraform destroy -auto-approve